dt<-read.csv("~/r/household_power_consumption.txt",nrows=-1L,header=T, na.strings="?", colClasses=c("character","character","numeric","numeric","numeric","numeric","numeric","numeric","numeric"),sep=";")
d1<- subset(dt, Date=="1/2/2007")
d2<- subset(dt, Date=="2/2/2007")
nd<-rbind(d1,d2)
x<-strptime(nd$Date,"%d/%m/%Y")
datetime<-paste(as.Date(x),nd$Time)
xx<-as.POSIXct(datetime)
plot(nd$Global_active_power~xx,type="l",ylab="Global Active Power (kilowatts)",xlab="")
dev.copy(png,filename="plot2.png",width = 480, height = 480, units = "px")
dev.off()