#require(data.table) load fast but leads to non numeric prob while plotting using hist()
#dt<-fread("household_power_consumption.txt",nrows=-1L,header="auto", na.strings="?", colClasses=c("character","character","numeric","numeric","numeric","numeric","numeric","numeric","numeric"))
dt<-read.csv("household_power_consumption.txt",nrows=-1L,header=T, na.strings="?", colClasses=c("character","character","numeric","numeric","numeric","numeric","numeric","numeric","numeric"),sep=";")
d1<- subset(dt, Date=="1/2/2007")
d2<- subset(dt, Date=="2/2/2007")
nd<-rbind(d1,d2)
hist(nd$Global_active_power,col="red",xlab="Global Active Power (kilowatts)",main="Global Active Power",ylim=c(0,1200),las=1)
dev.copy(png,filename="plot1.png",width = 480, height = 480, units = "px")
dev.off()